### ISSUE TITLE
Please upload the source files themself instead of a zip containing them to the repo

### ISSUE THREAD

**Issue by ben-hawks** [mantheman12/Candle-library#1]
It's a lot easier to view, track, fork, and generally work with the code if the source files are all uploaded individually to the repo instead of a zip file containing all of them. There's also some security concerns about downloading and unzipping an "unknown" zip archive for some folks.

Thanks for the great library!

**Comment by mantheman12** [comment]
> It's a lot easier to view, track, fork, and generally work with the code if the source files are all uploaded individually to the repo instead of a zip file containing all of them. There's also some security concerns about downloading and unzipping an "unknown" zip archive for some folks.
> 
> Thanks for the great library!

thanks, im a first time user of github, i just fixed the problem

**Comment by ben-hawks** [comment]
Awesome, Thanks! Closing the issue since it's been resolved
